mcl all-vs-all.tsv --abc -I 10.0
mcl all-vs-all.tsv --abc -I 8.0
mcl all-vs-all.tsv --abc -I 7.0
mcl all-vs-all.tsv --abc -I 6.0
mcl all-vs-all.tsv --abc -I 5.5
mcl all-vs-all.tsv --abc -I 4.5
mcl all-vs-all.tsv --abc -I 2.0
mcl all-vs-all.tsv --abc -I 2.5
mcl all-vs-all.tsv --abc -I 3.0
mcl all-vs-all.tsv --abc -I 3.5
mcl all-vs-all.tsv --abc -I 4.0
mcl all-vs-all.tsv --abc -I 5.0
mcl all-vs-all.tsv --abc -I 1.0
mcl all-vs-all.tsv --abc -I 1.5
mcl all-vs-all.tsv --abc -I 0.5
